export const productosLM = [
    {nombre: "Mate Stanley", precio: 11500, desc:"Mate Stanley de acero inoxidable, no incluye bombilla", categoria: "Mates", img: "./", stock:10, id: 1},
    {nombre: "Mate Calabaza", precio: 9500, desc:"Mate de calabaza, con borde de acero inoxidable, no incluye bombilla", categoria: "Mates", img: "./", stock:10 ,id: 2},
    {nombre: "Mate Plastico", precio: 700, desc:"Mate de plastico duro de colores, con sistema autolimpiante con bombilla de alumino", categoria: "Mates", stock:10, img: "./",id: 3},
    {nombre: "Mate Autocebante", precio: 640, desc:"Mate Autocebante de plastico de 500ml. Con tapa y bombilla", categoria: "Mates", img: "./", stock:10,id: 4},
    {nombre: "Termo Stanley", precio: 16999, desc:"Termo Stanley de acero inoxidable de 950mlt", categoria: "Termos", img: "./", stock:10,id: 5},
    {nombre: "Termo Acero", precio: 3900, desc:"Termo Acero Inoxidable, Marca Heizen, Con Manija, 1 Litro, Color Gris", categoria: "Termos", img: "./", stock:10,id: 6},
    {nombre: "Termo Plastico", precio: 1500, desc:"Termo de plástico de 1lts con pico cebador a rosca", categoria: "Termos", img: "./", stock:10,id: 7},
    {nombre: "Termo Terere", precio: 3600, desc:"Termo de plastico de 2,5lts, para bebidas frias", categoria: "Termos", img: "./", stock:10,id: 8},
    {nombre: "Bombilla Espiral", precio: 300, desc:"Bombilla Espiral", categoria: "Bombillas", img: "./", stock:10,id: 9},
    {nombre: "Bombilla Metal", precio: 400, desc:"Bombilla de Metal", categoria: "Bombillas", img: "./", stock:10,id: 10},
    {nombre: "Bombilla Alpaca", precio: 900, desc:"Bombilla Alpaca", categoria: "Bombillas", img: "./", stock:10,id: 11},
    {
    nombre: "Bombilla Plana",
    precio: 900,
    desc:"Bombilla Plana",
    categoria: "Bombillas",
    img: "./",
    stock:10,
    id: 12},
]